xfreerdp3 \
	/log-level:FATAL \
	/v:ws001 \
	/u:marcellusv@gateway.com \
	/gateway:g:remote.gateway.com \
	/audio-mode:1 \
	/size:1920x1080 \
	/compression \
	/compression-level:2 \
	/gdi:hw \
	/gfx:AVC444:on \
	/frame-ack:on \
	/bpp:8 \
	/auth-pkg-list:!kerberos \
	+clipboard \
	+dynamic-resolution \
	-wallpaper \
	-fonts \
	-themes \
	-decorations \
